# Generated by Django 5.1.8 on 2025-04-05 06:30

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('descriptions', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True,
                 upload_to=courses.models.handle_upload)),
                ('access', models.CharField(choices=[
                 ('any', 'Anyone'), ('email_required', 'Email required')], default='email_required', max_length=20)),
                ('status', models.CharField(choices=[('pub', 'Published'), (
                    'draft', 'Draft'), ('soon', 'Coming soon')], default='draft', max_length=20)),
            ],
        ),
    ]
