# Generated by Django 5.1.8 on 2025-04-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descriptions',
            new_name='description',
        ),
    ]
