# Generated by Django 5.1.8 on 2025-04-05 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lesson_preview_lesson_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='preview',
            new_name='can_preview',
        ),
    ]
