# Generated by Django 5.1.8 on 2025-04-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_course_timestamp_course_updated_alter_course_access_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
