# Generated by Django 5.1.8 on 2025-04-19 10:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_course_timestamp_alter_lesson_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
